// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/consignment/consignment.proto

/*
Package consignment is a generated protocol buffer package.

It is generated from these files:
	proto/consignment/consignment.proto

It has these top-level messages:
	Consignment
	Container
	GetRequest
	Response
*/
package consignment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ConsignmentService service

type ConsignmentService interface {
	Create(ctx context.Context, in *Consignment, opts ...client.CallOption) (*Response, error)
	Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
}

type consignmentService struct {
	c    client.Client
	name string
}

func NewConsignmentService(name string, c client.Client) ConsignmentService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "consignment"
	}
	return &consignmentService{
		c:    c,
		name: name,
	}
}

func (c *consignmentService) Create(ctx context.Context, in *Consignment, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ConsignmentService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consignmentService) Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ConsignmentService.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ConsignmentService service

type ConsignmentServiceHandler interface {
	Create(context.Context, *Consignment, *Response) error
	Get(context.Context, *GetRequest, *Response) error
}

func RegisterConsignmentServiceHandler(s server.Server, hdlr ConsignmentServiceHandler, opts ...server.HandlerOption) error {
	type consignmentService interface {
		Create(ctx context.Context, in *Consignment, out *Response) error
		Get(ctx context.Context, in *GetRequest, out *Response) error
	}
	type ConsignmentService struct {
		consignmentService
	}
	h := &consignmentServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ConsignmentService{h}, opts...))
}

type consignmentServiceHandler struct {
	ConsignmentServiceHandler
}

func (h *consignmentServiceHandler) Create(ctx context.Context, in *Consignment, out *Response) error {
	return h.ConsignmentServiceHandler.Create(ctx, in, out)
}

func (h *consignmentServiceHandler) Get(ctx context.Context, in *GetRequest, out *Response) error {
	return h.ConsignmentServiceHandler.Get(ctx, in, out)
}
