apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: data-volume-TYPE-SIZEg-INSTANCE
spec:
  capacity:
      storage: SIZEGi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  gcePersistentDisk:
    fsType: ext4
    pdName: pd-ssd-disk-TYPE-SIZEg-INSTANCE